


class UnexpectedError(Exception) :
    pass
class ObjectNotFound(Exception) :
    pass